### ISSUE TITLE
Process and optimize media

### ISSUE THREAD

**Issue by fhoshino** [sekai-soft/pill-city#135]

**Comment by yume-chan** [comment]
Support image resizing/optimization/format conversion (for example with [Serverless Image Handler](https://docs.aws.amazon.com/solutions/latest/serverless-image-handler/cost.html))

**Comment by KTachibanaM** [comment]
Upload an original media and trigger a background job to
* Convert to WebP and resize
* Compute width, height and dominant color

Trigger the job for existing media as well if they are accessed

Read APIs with media should return backwards compatible response with new media info once media is processed
"backwards compatible" == retain `media_urls` and add `media_urls_2`
* Get post (including reshared post)
* Get comment and nested comment
* ~Get owned media & media set (sticker pack)~
* Get user

On UI, display dominant color while loading the actual (WebP + fallback) image (lazy loading)

When expanded, you should also be able to download the original image

Also replace static images with WebP

New media model fields needed
* processed
* processing
* width
* height
* dominant color

**Comment by KTachibanaM** [comment]
Resolved in

https://github.com/pill-city/server/pull/358

https://github.com/pill-city/server/pull/359

https://github.com/pill-city/server/pull/360

https://github.com/pill-city/server/pull/362
