### ISSUE TITLE
Rich text parsing/storage format

### ISSUE THREAD

**Issue by yume-chan** [sekai-soft/pill-city#164]
Currently, post contents are stored as plain text -- rich text styles such as bold, italic and strikethrough are implemented in front end.

As a result, each front end must implement their own parsing logic, and ensure all implementations are consistent.

---

So, I propose that:

1. Backend should store and transmit post contents in a deterministic, machine parseable format.
2. Backend should be able to accept new post in both plain text and the aforementioned format, and parse the former into the latter (on some platforms, it may be easier to use a format toolbar or menu, instead of requiring users to type specific characters, to trigger special styles, clients on such platforms can submit content in parsed format directly, simplify its design).

---

As an example, the format can be a flatted array:

```json
[
    "normal text ",
    ["bold text ", "bold"],
    ["bold and italic ", ["bold italic"],
    ["bold link ", "bold link"]
]
```

Renders as 

normal text **bold text** _**bold and italic**_ **[bold link](https://www.google.com)**

**Comment by KTachibanaM** [comment]
This was implemented in https://github.com/pill-city/server/pull/418 and is being used in the new Flutter app
