### ISSUE TITLE
Notification indicator on mobile may not be up-to-date and flickering

### ISSUE THREAD

**Issue by KTachibanaM** [sekai-soft/pill-city#220]
Also a good chance to 1) implement more efficient notification polling 2) move notification polling to top-level App component 3) replace HoC's with hooks

**Comment by innkuika** [comment]
A quick fix can be to set a timer and have nav bar to pull every x seconds.

Also the navigation bar is pulling all notifications now. Probably should add an API for getting notification indicator.
