### ISSUE TITLE
Default Emoji font weight on Windows with Chromium 96+ not being shown correctly

### ISSUE THREAD

**Issue by fhoshino** [sekai-soft/pill-city#235]
After Chromium 96, emoji on Windows fallbacked to black & white set
![brave_2021-11-20_02-14-18](https://user-images.githubusercontent.com/771955/142724551-728826fe-68e1-432e-ad54-8ecbc951aba0.png)
Which prior 96 there is no fallback issue

As @yume-chan menioned this might be a font weight problem
![photo1637381768](https://user-images.githubusercontent.com/771955/142724624-2afa4901-8207-42fb-a9d1-3d9971de2286.jpeg)

**Comment by KTachibanaM** [comment]
Fixed in https://github.com/pill-city/pill-city/commit/cbe404a6ea07985d3d0003af13d312702fa44f40
