### ISSUE TITLE
Bugg layout for comments.

### ISSUE THREAD

**Issue by HerringtonDarkholme** [sekai-soft/pill-city#381]
Expect: comment should wrap from the beginning of a post.
Actual: comment wraps from the beginning of author's name.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/2883231/174520540-17f8739e-5241-4075-a61e-35ed48534fdf.png">

**Comment by HerringtonDarkholme** [comment]
Using float:left looks nicer, how about this?

<img width="433" alt="image" src="https://user-images.githubusercontent.com/2883231/174523851-5f8a2fbc-5df1-4afb-8a05-1e10d0a7f3b5.png">

**Comment by KTachibanaM** [comment]
looks better. feel free to open an MR
