### ISSUE TITLE
Fix post interactions on profile, post page and mobile view

### ISSUE THREAD

**Issue by KTachibanaM** [sekai-soft/pill-city#81]

**Comment by innkuika** [comment]
Check table

Desktop
|             | Home | Post Detail | Profile |
|-------------|------|-------------|---------|
| Reaction | X  |     X        |    X     |
| Reshare     |  X   |             |         |
| Comment     | X  |  X           |   X      |

Mobile
|             | Home | Post Detail | Profile |
|-------------|------|-------------|---------|
| Reaction |  X    |       X      |   X      |
| Reshare     |   X   |             |         |
| Comment     |  X    |     X        |     X    |
