### ISSUE TITLE
Block/Unblock users

### ISSUE THREAD

**Issue by fhoshino** [sekai-soft/pill-city#94]
Ability to block a user in order not to show his/her posts and prevent him/her to read the owner's timeline.

**Comment by RotoDhoulmagus** [comment]
Enhancement: Levelled Blocked Users
Level 1: All of his posts, comments, along with his avatar and name are blurred or blacked, and shows a OSD saying "Blocked User. Click to show"
Level 2: All of his comments are replaced with a placeholder saying "Blocked User.", like Twitter's behaviour. 
Level 3: Absolutely nothing shows, as if there does not exist his comment.

**Comment by KTachibanaM** [comment]
Ability to block a user in order not to show his/her posts + All of his comments are replaced with a placeholder saying "Blocked User." is implemented in this issue. Other behaviors will be implemented in #411
